version: '2'
services:
  nginx:
     image: nginx:1.13.12-alpine
     container_name: nemesis-nginx
     volumes:
      - ./site.template:/etc/nginx/conf.d/site.template
      - ./server.crt:/etc/nginx/ssl/server.crt
      - ./server.key:/etc/nginx/ssl/server.key
     ports:
      - "80:80"
      - "443:443"
     links:
      - app
     environment:
      - NGINX_HOST=test
      - DOLLAR=$$
     command: /bin/sh -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  app:
     image: nemesis/samplestore
     container_name: nemesis-app
     ports:
      - "8111:8111"
      - "8112:8112"
      - "8000:8000"
     links:
      - db
      - redis
      - elasticsearch
     depends_on:
      - db
      - redis
      - elasticsearch
  console:
     image: nemesis/console
     container_name: nemesis-console
     ports:
      - "8443:8443"
  db:
     image: mysql:5.6.40
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
     container_name: nemesis-db
     env_file:
       - 'dev.env'
  redis:
     image: redis:4.0.9-alpine
     container_name: nemesis-redis
  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
     container_name: nemesis-elasticsearch
     environment:
      - cluster.name=nemesis-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
     ports:
      - "9300:9300"
      - "9200:9200"
  prometheus:
     image: prom/prometheus
     container_name: nemesis-prometheus
     volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
     command:
      - --config.file=/etc/prometheus/prometheus.yml
     ports:
      - "9090:9090"
  grafana:
     image: grafana/grafana
     container_name: nemesis-grafana
     environment:
      - GF_SECURITY_ADMIN_PASSWORD=nimda
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,briangann-gauge-panel,grafana-clock-panel
     links:
      - prometheus
     ports:
      - "3000:3000"
