{
 "title": "Nemesis Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Active sessions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "tomcat_sessions_active_current",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Datasource Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jdbc_connections_max", "legendFormat": "MAX" },
    { "expr": "jdbc_connections_active", "legendFormat": "ACTIVE" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "TOMCAT" },
    { "expr": "system_cpu_usage", "legendFormat": "SYSTEM" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "MAX BYTES" },
    { "expr": "jvm_memory_used_bytes", "legendFormat": "USED BYTES" }
   ]
  },
  {
   "title": "Threads Live",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live", "legendFormat": "JVM THREADS LIVE" },
    { "expr": "jvm_threads_peak", "legendFormat": "JVM THREADS PEAK" }
   ]
  },
  {
   "title": "ExecutorService",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "active", "metric": "executorService_active" },
    { "expr": "jvm", "legendFormat": "completed" },
    { "expr": "executorService_queue_size", "legendFormat": "queued" }
   ]
  }
 ]
}