global:
  scrape_interval: 5s
scrape_configs:
- job_name: app
  basic_auth:
      username: admin
      password: nimda
  metrics_path: /platform/prometheus
  scheme: http
  static_configs:
  - targets:
    - app:8111
