version: '2'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nemesis-nginx
    volumes:
      - ../full/nginx/site.template:/etc/nginx/conf.d/site.template
      - ../full/nginx/server.crt:/etc/nginx/ssl/server.crt
      - ../full/nginx/server.key:/etc/nginx/ssl/server.key
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    environment:
      - NGINX_HOST=test
      - DOLLAR=$$
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  app:
    image: nemesis/democms:latest
    container_name: nemesis-app
    environment:
      - "NEMESIS_JAVA_OPTS=-Xms1.5g -Xmx1.5g -Xss512K -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:CompressedClassSpaceSize=128m -XX:+HeapDumpOnOutOfMemoryError"
      - spring.profiles.active=docker
      - NEMESIS_PLATFORM_CONSOLE_URL=https://${DOCKER_HOST_IP}:8443/backend/
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - elasticsearch
    depends_on:
      - db
      - redis
      - elasticsearch
  console:
    image: nemesis/console
    container_name: nemesis-console
    ports:
      - "8443:8443"
    environment:
      - NEMESIS_CONSOLE_WEBSITE_URL=https://${DOCKER_HOST_IP}/
      - NEMESIS_CONSOLE_WEBSITE_REST_URL=https://${DOCKER_HOST_IP}/rest/
  db:
    image: mysql:8.0.18
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    container_name: nemesis-db
    env_file:
      - './mysql/dev.env'
    security_opt:
      - seccomp:unconfined
  redis:
    image: redis:4.0.9-alpine
    container_name: nemesis-redis
  # the host needs this sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    container_name: nemesis-elasticsearch
    hostname: nemesis-elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    cap_add:
      - IPC_LOCK
    environment:
      - cluster.name=nemesis-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9300:9300"
      - "9200:9200"
