version: '2'
services:
  nginx:
     image: nginx:1.13.12-alpine
     container_name: nemesis-nginx
     volumes:
      - ./site.template:/etc/nginx/conf.d/site.template
      - ./server.crt:/etc/nginx/ssl/server.crt
      - ./server.key:/etc/nginx/ssl/server.key
     ports:
      - "80:80"
      - "443:443"
     links:
      - app
     environment:
      - NGINX_HOST=test
      - DOLLAR=$$
     command: /bin/sh -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  app:
     image: nemesis/samplestore:latest
     container_name: nemesis-app
     environment:
         spring.profiles.active: docker
     environment:
      - NEMESIS_PLATFORM_CONSOLE_URL=https://207.154.222.231:8443/backend/
     ports:
      - "8000:8000"
     links:
      - db
      - redis
      - elasticsearch
      - logstash
     depends_on:
      - db
      - redis
      - elasticsearch
  console:
     image: nemesis/console
     container_name: nemesis-console
     ports:
      - "8443:8443"
     environment:
      - NEMESIS_CONSOLE_WEBSITE_URL=https://207.154.222.231/
      - NEMESIS_CONSOLE_WEBSITE_REST_URL=https://207.154.222.231/rest/
  db:
     image: mysql:5.6.40
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
     container_name: nemesis-db
     env_file:
       - 'dev.env'
  redis:
     image: redis:4.0.9-alpine
     container_name: nemesis-redis
 # the host needs this sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
     container_name: nemesis-elasticsearch
     hostname: nemesis-elasticsearch
     ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
     mem_limit: 4g
     cap_add:
      - IPC_LOCK
     environment:
      - cluster.name=nemesis-cluster
      - "ES_JAVA_OPTS=-Xms1750m -Xmx1750m"
      - xpack.security.enabled=false
     ports:
      - "9300:9300"
      - "9200:9200"
  logstash:
     image: docker.elastic.co/logstash/logstash:6.4.3
     container_name: nemesis-logstash
     ports:
      - '5000:5000'
      - '9600:9600'
     command: logstash -f /usr/share/logstash/pipeline/logstash.conf
     volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
     links:
      - elasticsearch
     depends_on:
      - elasticsearch
  kibana:
     image: docker.elastic.co/kibana/kibana:6.4.3
     container_name: nemesis-kibana
     environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
     ports:
      - '5601:5601'
     links:
      - elasticsearch
     depends_on:
      - elasticsearch
  grafana:
     image: grafana/grafana
     container_name: nemesis-grafana
     environment:
      - GF_SECURITY_ADMIN_PASSWORD=nimda
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,briangann-gauge-panel,grafana-clock-panel
     links:
      - prometheus
     ports:
      - "3000:3000"
  prometheus:
     image: prom/prometheus
     container_name: nemesis-prometheus
     volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
     command:
      - --config.file=/etc/prometheus/prometheus.yml
     ports:
      - "9090:9090"
     links:
      - nginx
     depends_on:
      - nginx
