global:
  scrape_interval: 5s
scrape_configs:
- job_name: app
  basic_auth:
      username: admin
      password: nimda
  metrics_path: /storefront/platform/prometheus
  scheme: http
  static_configs:
  - targets:
    - 172.17.0.1:8111
